export const Extension = {
  PDF:  '.pdf',
  CSV:  '.csv',
  XLS:  '.xls',
  XLSX: '.xlsx',
  XML:  '.xml',
  GIF:  '.gif',
  JPEG: '.jpeg',
  JPG:  '.jpg',
  PNG:  '.png',
  SVG:  '.svg',
  TIFF: '.tiff',
  ICO:  '.ico',
  WBMP: '.wbmp',
  WEBP: '.webp',
  TXT:  '.txt',
};